name: 编译exe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka

    - name: Download and extract UPX
      run: |
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v5.0.2/upx-5.0.2-win64.zip" -OutFile "upx.zip"
        Expand-Archive -Path "upx.zip" -DestinationPath "D:\"

    - name: Compile with Nuitka
      shell: cmd
      run: >
        python -m nuitka
        --clang
        --onefile
        --onefile-no-compression
        --assume-yes-for-downloads
        --msvc=latest
        --output-dir=dist
        --enable-plugin=upx
        --upx-binary=D:\upx-5.0.2-win64
        --include-data-files=shapes.json=shapes.json
        main.py

    - name: Upload dist as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuitka-dist
        path: dist/main.exe
